const products = [
    {
        id: 1,
        image: "../../public/images/prod1.webp",
        name: "ACTION 90",
        category: "Agro Chemical",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Activator, Spreader, Sticker & ph Controller",
    },
    {
        id: 2,
        image: "../../public/images/prod2.webp",
        name: "3G Bordo",
        category: "Agro Chemicalls",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Powder Bordo",
    },
    {
        id: 3,
        image: "../../public/images/prod3.webp",
        name: "GREEN WET",
        category: "Agro Chemicalls",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Sillion Based Non lonic Surfactant",
    },
    {
        id: 4,
        image: "../../public/images/prod4.webp",
        name: "NEEMAMRUT",
        category: "Agro Chemicalls",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Neem Oil",
    },
    {
        id: 5,
        image: "../../public/images/prod5.webp",
        name: "BIO SOLDIER",
        category: "Bio Stimulants",
        subCategory: "Biostimullants - Botanical, Plant Extract & Seaweed Extract",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Biological Extract",
    },
    {
        id: 6,
        image: "../../public/images/prod5.webp",
        name: "BIO KILLER",
        category: "Bio Stimulants",
        subCategory: "Biostimullants - Botanical, Plant Extract & Seaweed Extract",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Herbal Pest Repellent",
    },
    {
        id: 7,
        image: "../../public/images/prod5.webp",
        name: "FUNG-CLEAN",
        category: "Bio Stimulants",
        subCategory: "Biostimullants - Botanical, Plant Extract & Seaweed Extract",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Organic fungicide",
    },
    {
        id: 8,
        image: "../../public/images/prod5.webp",
        name: "RAKSHAK",
        category: "Bio Stimulants",
        subCategory: "Biostimullants - Botanical, Plant Extract & Seaweed Extract",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Organic Dusting Powder",
    },



    {
        id: 9,
        image: "../../public/images/prod2.webp",
        name: "3G HUMIC (Liquid)",
        category: "Bio Stimulants",
        subCategory: "Biostimullants - Humic, Fulvic Acid & their Derivatives",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Humic Acid 15% + Seaweed Extract 3%",
    },
    {
        id: 10,
        image: "../../public/images/prod2.webp",
        name: "3G HUMIC (Powder/Crystal/Flex)",
        category: "Bio Stimulants",
        subCategory: "Biostimullants - Humic, Fulvic Acid & their Derivatives",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Humic Acid 65% Crystal",
    },
    {
        id: 11,
        image: "../../public/images/prod2.webp",
        name: "SUPER ROBOT PLUS",
        category: "Bio Stimulants",
        subCategory: "Biostimullants - Humic, Fulvic Acid & their Derivatives",
        price: "300",
        weight: [500, 300, 200, 100],
        desc: "Advance Humic Acid With Extra Fulvic Acid & Amino Acid",
    },
]

export default products;